## Add OpenJDK 6 to Android Build environment

FROM android-builder-base
MAINTAINER Tom Hiller

ENV DEBIAN_FRONTEND noninteractive

## Install OpenJDK 6
RUN apt-get install -y openjdk-6-jdk openjdk-6-jre
