## Add OpenJDK 6 to Android Build environment

FROM android-builder-base
MAINTAINER Tom Hiller

ENV DEBIAN_FRONTEND noninteractive

## Install OpenJDK 7
RUN apt-get install -y openjdk-7-jdk openjdk-7-jre
